version: 2
jobs:
  build:
    docker:
      - image: adobe/commerce-cif-ci-env:ci-v0.0.2
    steps:
      - checkout
      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "pom.xml" }}
            - maven-repo-v1-
      - run:
          name: Build
          command: node ci/build.js
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports
      - store_artifacts:
          path: audit.json
  release:
    docker:
      - image: adobe/commerce-cif-ci-env:ci-v0.0.2
    steps:
      - checkout
      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "pom.xml" }}
            - maven-repo-v1-
      - run:
          name: Release
          command: cd ci; npm ci; cd ..; node ci/release.js

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^@release-(major|minor|patch)$/